CREATE SEQUENCE user_id_sequence START 1 increment by 1;

DROP TABLE IF EXISTS "user_account";
CREATE TABLE "user_account" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);
